### ISSUE TITLE
can I have https at local port

### ISSUE THREAD

**Issue by iamike** [aspendigital/docker-octobercms#11]
when I was developing at local site. sometimes I need using ngrok to reflect the local environment to the outside world. but it seems it doesn't have some config that can let me to do this. 
so How can I have 127.0.0.1:443 open?
ideally, if I can set ports at docker-compose file just like this:
```
    ports:
      - 80:80
      - 443:443
```
it will be great.

I tried:
```
ports:
      - 80:80
      - 443:80
```
but the template still using http:// not https for the source files

**Comment by iamike** [comment]
sorry, I fixed it.
no need for mirror 2 port
just 80 is enough,
this one is  **crucial**

`CMS_LINK_POLICY=secure`

**Comment by petehalverson** [comment]
Whenever the container is behind a proxy, you'll need to use`CMS_LINK_POLICY=secure`.

I should point out [`CMS_BACKEND_FORCE_SECURE` defaults to `false`](https://github.com/aspendigital/docker-octobercms#october-cms-app-environment-config) for this purpose as well.
