### ISSUE TITLE
nginx and mariadb version ?

### ISSUE THREAD

**Issue by DigitalCoder** [aspendigital/docker-octobercms#17]
Hi,
I'm looking for docker image working on Ubuntu last version (18.04) with :

Nginx
PHP last version (7.1 / 7.2) PHP-FPM
Mariadb
Octobercms (last release)

Thx

**Comment by petehalverson** [comment]
Sorry, this image is based on [Docker's official PHP images](https://hub.docker.com/_/php) which use Debian.

I typically stick to separating services into their own containers and don't bundle nginx or mariadb into the October CMS image. [Checkout the README for an example that uses docker-compose](https://github.com/aspendigital/docker-octobercms#database-support).

Please let me know if you'd be interested in more examples. I should update and publish more...
