### ISSUE TITLE
Always the edge core version gets installed

### ISSUE THREAD

**Issue by fresswolf** [aspendigital/docker-octobercms#22]
No matter which tag I choose, this always installs the latest edge version of october. 

For example, when running  aspendigital/octobercms:build.455-php7.1-apache, the composer.json will contain the following dependencies:
`"october/system": "~1.0"`

This will result in the following resolved dependencies (composer.lock):
`

               "name": "october/system",
               "version": "v1.0.457",
                "source": {
                    "type": "git",
                    "url": "https://github.com/octoberrain/system.git",
                    "reference": "55239f2d0113b5dac77fd9ff4d3f1a61525f348d"
                }`

**Comment by petehalverson** [comment]
Thank you @fresswolf ! So glad you caught this!

While the October CMS codebase in the image was matching that of the build tag, composer dependencies were not.

I don't recall my reasoning for removing it in the past, but I restored a part of the build process that [matches build dependencies to the tag](https://github.com/aspendigital/docker-octobercms/blob/dc2a988022a8d0f5068e5b3f58f32c5f6c04e7d4/Dockerfile.template#L44-L47).

The automated build [checks out](https://travis-ci.org/aspendigital/docker-octobercms/jobs/563307665#L2525-L2530) and has been published to the Docker Hub. 

Retry it locally, but be sure to pull the new image:

```
$ docker pull aspendigital/octobercms:build.455-php7.1-apache
$ docker run --rm aspendigital/octobercms:build.455-php7.1-apache composer info | grep october

october/backend                   v1.0.455           Backend module f...
october/cms                       v1.0.455           CMS module for O...
october/rain                      v1.0.455           October Rain Lib...
october/system                    v1.0.455           System module fo...

```

I think we should include that as part of the automated build test.  At the moment, I only report it for reference.

**Comment by fresswolf** [comment]
Thank you for the quick fix. I agree that a test would help, as the way the october repo is tagged is a bit misleading (The tags are more or less useless when using composer)
