### ISSUE TITLE
error when : artisan october:up

### ISSUE THREAD

**Issue by putrarifin** [aspendigital/docker-octobercms#25]
when i try to : docker-compose exec web php artisan october:up

i got this message : Could not open input file: artisan

inside container var/www/html/ there is 3 folder only nothing else. no composer and artisan file

**Comment by petehalverson** [comment]
Hi @putrarifin! Check what volumes you've defined in your `docker-compose.yml`. It sounds like you've mapped it to some working folder and overwritten the codebase.
