### ISSUE TITLE
how to set PHP max_execution_time ?

### ISSUE THREAD

**Issue by iamike** [aspendigital/docker-octobercms#31]
how can I increase this php params ?
because I want upload some big file on backend.
is there any elegant way like just set:
"PHP_POST_MAX_SIZE","PHP_MEMORY_LIMIT","PHP_UPLOAD_MAX_FILESIZE" ?

thanks
<img width="1212" alt="截屏2020-03-23下午7 48 27" src="https://user-images.githubusercontent.com/526854/77314476-b037c180-6d40-11ea-930d-687aa751315e.png">

**Comment by petehalverson** [comment]
While I have made a few PHP config variable triggers, I hadn't intended it to be all encompassing.

See the README notes for [PHP Configuration](https://github.com/aspendigital/docker-octobercms#php-configuration).

You could use a volume mount to add a custom config to your container or extend the image itself and append your custom setting to the existing PHP config:

```dockerfile
FROM aspendigital/octobercms:latest
RUN echo 'max_execution_time=90' >> /usr/local/etc/php/conf.d/docker-oc-php.ini
```

**Comment by petehalverson** [comment]
I am open to adding support for this and settings should more users show interest.
