### ISSUE TITLE
Installing Plugin Dependencies on `docker-compose up`

### ISSUE THREAD

**Issue by damanic** [aspendigital/docker-octobercms#41]
I have used this docker package on a project with a custom plugin mapped as a volume. This plugin has a bunch of free marketplace plugins listed as dependencies in  `Plugin::$require` .

I was hoping octoberCMS would catch this on install, and add all the dependencies for my Plugin - but it's not that slick.

What is the recommended way to install a list of octoberCMS plugins on docker-compose up?

**Comment by petehalverson** [comment]
We typically use git submodules to manage plugins and trigger install using the [`INIT_PLUGINS=true` environment variable](https://github.com/aspendigital/docker-octobercms#docker-entrypoint) set in the docker-compose. 

This method works well when you want to keep plugins under version control. 

If you're looking to install plugins via the marketplace, I would extend the entrypoint script to run the plugin install commands.
