### ISSUE TITLE
Trying to user PHP 7.4-apache Dockerfile : Composer Error

### ISSUE THREAD

**Issue by boyer-nicolas** [aspendigital/docker-octobercms#42]
Hi,
I'm trying to use the PHP 7.4-apache Dockerfile and I'm getting the following errors : 
```bash
[RuntimeException] No composer.json present in the current directory, this may be the cause of the following exception.

[InvalidArgumentException]
Package hirak/prestissimo has a PHP requirement incompatible with your PHP version, PHP extensions and Composer version
```

Basically it fails at this command : 
```bash
RUN curl -sS https://getcomposer.org/installer | php -- --install-dir=/usr/local/bin --filename=composer && \
/usr/local/bin/composer global require hirak/prestissimo
```

I'm trying to build this with the whole PHP 7.4-apache folder.

Any ideas ?

**Comment by LukeTowers** [comment]
@jimcottrell @petehalverson this is because of Composer 2.0 being the version of composer pulled from getcomposer.org, and prestissimo is no longer helpful. I would just get rid of prestissimo. Also note that you may need to make some other adjustments so that these images work with the 1.1 branch of October, and that Composer 2.0 will only work with build 1.1.1+

**Comment by boyer-nicolas** [comment]
@LukeTowers Thanks for your answer. So basically I'm not using the latest october version even tho I'm trying to build the latest available on this repo  ?

**Comment by LukeTowers** [comment]
@boyer-nicolas if you're using the develop image then that's the latest version of October. The 1.1 comment I mentioned is more for @aspendigital's reference as it will probably change some things about how they structure their automated builds of the images.

**Comment by boyer-nicolas** [comment]
Alright, I thought it was the other way around ! I'll try this. Thanks !
