### ISSUE TITLE
how can i change the default APP_KEY

### ISSUE THREAD

**Issue by iamike** [aspendigital/docker-octobercms#9]
can i can the default APP_KEY?
Am I need put APP_KEY in .env file?
if everybody using the default APP_KEY, is that will be a problem for security? Thanks

**Comment by iamike** [comment]
sorry, I am a little bit confused here. 
if .env the file can handle the ENV variables, we just make 2 .env files, one for dev environment, and another is for live environment. in some cloud service, there might be kubernetes can also handle the environment. so which way is the best approach?

**Comment by petehalverson** [comment]
When using the image's `docker` config, if `APP_KEY` is not defined in your .env, it will fall back to the generic key set in [config/docker/app.php](https://github.com/aspendigital/docker-octobercms/blob/d3b288b9fe0606e32ac3d6466affd2996394bdca/config/docker/app.php#L11). This is to facilitate quick testing environment for developers without forcing them to configure settings.

[More about the App Environment](https://github.com/aspendigital/docker-octobercms#app-environment)

I typically maintain a separate docker-compose for each environment (local, stage, prod) within the project repo. I store secrets in `.env` that's not committed. Keep in mind, [docker-compose supports .env variables as well](https://docs.docker.com/compose/env-file/).

In practice, the best approach really depends on the project and to an extent, your preference.

If you're planning to deploy via swarm or kubernetes, it's a good idea to extend the image so you're not dependent on volume mounts which may include baking in your own config.
